[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"

[rpc_endpoints]
base = "https://mainnet.base.org"
baseSepolia = "https://sepolia.base.org"
zora = "https://rpc.zora.energy"
zoraSepolia = "https://sepolia.rpc.zora.energy"

[etherscan]
baseSepolia = { key = "", url = "https://api-sepolia.basescan.org/api" }
base = { key = "$BASESCAN_API_KEY", url = "https://api.basescan.org/api" }
zora = { key = "", url = "https://explorer.zora.energy", chainid = 7777777 }
zoraSepolia = { key = "", url = "https://sepolia.explorer.zora.energy", chainid = 999999999 }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
